# Generated by Django 4.0.5 on 2022-07-09 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0003_empleado_habilidades_empleado_avatar_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empleado',
            old_name='Habilidades',
            new_name='habilidades',
        ),
    ]
